ALTER TABLE todos ADD COLUMN owner varchar(255) NOT NULL DEFAULT 'foo';
ALTER TABLE todos ADD COLUMN create_date timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE todos ADD COLUMN modify_date timestamp NOT NULL  DEFAULT CURRENT_TIMESTAMP;
