spring:
    jpa:
        generate-ddl: false
        hibernate:
            ddl-auto: none

security:
    user:
        password: password
    oauth2:
        client:
            client-id: todolist-server
            client-secret: todo_server_secret
        resource:
            id: service
            userInfoUri: https://798f5d15-918b-4cb8-9709-bd0e2f8c0058.predix-uaa.run.aws-usw02-pr.ice.predix.io/userinfo
            token-info-uri: https://798f5d15-918b-4cb8-9709-bd0e2f8c0058.predix-uaa.run.aws-usw02-pr.ice.predix.io/check_token

logging:
    level:
        org: INFO
        com: INFO